name: Hello CI
on: push

permissions: write-all
  
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: |
          echo "Hello from GitHub Actions!"
          echo '2 + 2 = 4'

      - name: Show date
        run: date

      - name: Show runner info
        run: |
          echo "Runner OS: $RUNNER_OS"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF"
          echo "Triggered by: $GITHUB_ACTOR"

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run custom script
        run: bash script.sh

      - name: Adding new file
        run: |
            git config --global user.email "torvalds@linux-foundation.org"
            git config --global user.name "torvalds"

            echo '======== STATUS 1 ========'
            git status
            git switch -c "i_hate_linux"
            echo 'linux sucks :(((((' > my-feelings-about-linux.txt

            echo '======== STATUS 2 ========'
            git status
            git add my-feelings-about-linux.txt

            echo '======== STATUS 3 ========'
            git status
            git commit -am "Added a new file"

            echo '======== STATUS 4 ========'
            git status
            git push origin i_hate_linux

            echo '======== STATUS 5 ========'
            git status



