name: Hello CI
on: 
  push
  

permissions: write-all
  
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: |
          echo "Hello from GitHub Actions!"
          echo '2 + 2 = 4'

      - name: Show date
        run: date

      - name: Show runner info
        run: |
          echo "Runner OS: $RUNNER_OS"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF"
          echo "Triggered by: $GITHUB_ACTOR"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run custom script
        run: bash script.sh

      - name: Adding new file
        run: |
            echo "sorry linus :("
            
  hello-world:
    runs-on: ubuntu-latest
    needs: greet

    steps:
      - name: hello-world
        run: |
          echo "hello world"
          python --version

